### ISSUE TITLE
Installation/Running Question

### ISSUE THREAD

**Issue by andrewcalimlim** [Elegant-Queueing/student-version#8]
In User Manual > How to Install > Step 8 it says

> Ensure you are connected to the correct API by looking at and editing the "API_URL" variable in the MainActivity class in Android Studio. If running localy [sic], this should be "http://10.0.2.2:8080" If running on an instance should be the url of that instance.

Where is the MainActivity class inside the project folder?

**Comment by andrewcalimlim** [comment]
Oh further question about User Manual > How To Run too:

> After following all the steps above, click the "run" button on the top of Android Studio to run the app on your emulator. The run button is a green arrow.

What is the run configuration I need to specify in Android Studio?

**Comment by amankagarwal** [comment]
MainActivity is in `app/java/com.example.q-student/MainActivity.java` 
You should run the app with the emulator (that you created in the previous steps) selected in Devices (left of the green run arrow)
